baseURL = '/'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'es-ES'
defaultContentLanguage = 'es'
theme = 'enchanted-lowkey'
title = 'Enhanced Lowkey Hugo'
enableRobotsTXT = true
summaryLength = 40
paginate = 5


[markup]
  [markup.highlight]
    anorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
